#!/usr/bin/env bash
set -e

# build docs
cd docs
make clean
make html
cd ..

# Prepare requirements.txt for ReadThedocs
requirements_rtd=requirements_rtd.txt
requirements=requirements.txt
requirements_doc=requirements_doc.txt

echo "# DO NOT EDIT THIS FILE" > $requirements_rtd
echo "# =====================" >> $requirements_rtd
echo "# IT IS AUTOMATICALLY GENERATED FROM $requirements AND $requirements_doc" >> $requirements_rtd
echo "# " >> $requirements_rtd
for src_file in $requirements $requirements_doc
do
  cat $src_file >> $requirements_rtd
done

# Open docs in browser
./open_docs.sh
